### ISSUE TITLE
Plugin title and description should be localizable

### ISSUE THREAD

**Issue by lostindark** [Dathwada/handynotes-travelguide#1]
Found the following in plugin code, but not present in translation.

addon.pluginName  = L["config_plugin_name"]
addon.description = L["config_plugin_desc"]

**Comment by Dathwada** [comment]
Thanks for the report.
Do you mean on Curseforge or in zhTW.lua ?

Yes L["config_plugin_name"] wasn't available on curseforge.

and L["config_plugin_desc"] you already localized.
![](http://puu.sh/GKGIH/a95addfaa6.png)

**Comment by lostindark** [comment]
The plugin name is showed on UI, which I prefer that to be localizable. Some of those are already localized. 
Even for those localized ones, the name on curseforge are still English.
![WoWScrnShot_110620_094656](https://user-images.githubusercontent.com/8030927/98398304-99b35180-2015-11eb-85db-e7f3c4bf06b7.jpg)

**Comment by Dathwada** [comment]
as you wish.

I added it on curseforge with a note.
![](http://puu.sh/GKL3G/e56e9276e0.png)
