### ISSUE TITLE
Pins are not up-to-date

### ISSUE THREAD

**Issue by LordZepp** [Dathwada/handynotes-travelguide#10]
All the pins are still for BC only.

**Comment by Dathwada** [comment]
Hi, are you sure you have downloaded the right version [WotLKC - v1](https://www.curseforge.com/wow/addons/handynotes-travelguide-classic/files/3960767)? And please check if you have 2 TravelGuides installed, if yes you can delete the HandyNotes: TravelGuide (BCC) folder and activate HandyNotes: TravelGuide.

**Comment by Dathwada** [comment]
I totally forgot that the Stormwind Harbor was added in WotLK.
I added some missing boats and updated the tram location, i'll check for some other missing nodes and bring an update soon (maybe in a few days).

**Comment by LordZepp** [comment]
Thank you!
