### ISSUE TITLE
Error handler.lua [Retail]

### ISSUE THREAD

**Issue by Hollicsh** [Dathwada/handynotes-travelguide#12]
27x ...rfaceHandyNotes_TravelGuide\core\handler.lua:83: attempt to index local 'poi' (a nil value)
[string "@HandyNotes_TravelGuide\core\handler.lua"]:83: in function <...rfaceHandyNotes_TravelGuide\core\handler.lua:78>
[string "=[C]"]: ?

Locals:
self = WorldMapFrame {
 0 = <userdata>
 ShouldPanOnClick = <function> defined @Blizzard_MapCanvas\Blizzard_MapCanvas.lua:683
 GetMinZoomViewRect = <function> defined @Blizzard_MapCanvas\Blizzard_MapCanvas.lua:703
 PanTo = <function> defined @Blizzard_MapCanvas\Blizzard_MapCanvas.lua:650
 HandleUserActionOpenSelf = <function> defined @FrameXML\QuestLogOwnerMixin.lua:91
 AreDetailLayersLoaded = <function> defined @Blizzard_MapCanvas\Blizzard_MapCanvas.lua:450
 RemovePin = <function> defined @Blizzard_MapCanvas\Blizzard_MapCanvas.lua:215
 OnCanvasScaleChanged = <function> defined @Blizzard_MapCanvas\Blizzard_MapCanvas.lua:590
 RemoveGlobalPinMouseActionHandler = <function> defined @Blizzard_MapCanvas\Blizzard_MapCanvas.lua:837
 OnQuestLogOpen = <function> defined @FrameXML\QuestLogOwnerMixin.lua:219
 CalculatePinNudging = <function> defined @Blizzard_MapCanvas\Blizzard_MapCanvas.lua:324
 OnCanvasSizeChanged = <function> defined @Blizzard_MapCanvas\Blizzard_MapCanvas.lua:606
 ApplyPinPosition = <function> defined @Blizzard_MapCanvas\Blizzard_MapCanvas.lua:510
 SetAreaTriggerIntersectsCallback = <function> defined @Blizzard_MapCanvas\Blizzard_MapCanvas.lua:270
 ShouldZoomInstantly = <function> defined @Blizzard_MapCanvas\Blizzard_MapCanvas.lua:691
 HandleUserActionToggleQuestLog = <function> defined @FrameXML\QuestLogOwnerMixin.lua:44
 NavBar = <unnamed> {
 }
 pinNudgingDirty = false
 SetGlobalPinScale = <function> defined =[C]:-1
 RefreshDebugAreaTriggers = <function> defined @Blizzard_MapCanvas\Blizzard_MapCanvas.lua:398
 SetShouldNavigateOnClick = <function> defined @Blizzard_MapCanvas\Blizzard_MapCanvas.lua:671
 NavigateToParentMap = <function> defined @Blizzard_MapCanvas\Blizzard_MapCanvas.lua:783
 SetDebugAreaTriggersEnabled = <function> defined @Blizzard_MapCanvas\Blizzard_MapCanvas.lua:422
 SetFocusedQuestID = <function> defined @Blizzard_WorldMap\Blizzard_WorldMap.lua:420
 UnregisterEvents = <function> defined @SharedXML\CallbackRegistry.lua:140
 EvaluateLockReasons = <function> defined @Blizzard_MapCanvas\Blizzard_MapCanvas.lua:753
 GetGlobalPinScale = <function> defined @Blizzard_MapCanvas\Blizzard_MapCanvas.lua:891
 SetDisplayState = <function> defined @FrameXML\QuestLogOwnerMixin.lua:99
 TitleCanvasSpacerFrame = <unnamed> {
 }
 OnLoad = <function> defined @Blizzard_WorldMap\Blizzard_WorldMap.lua:82
 RemoveDataProviderEvent = <function> defined @Blizzard_MapCanvas\Blizzard_MapCanvas.lua:128
 GetNumActivePinsByTemplate = <function> defined @Blizzard_MapCanvas\Blizzard_MapCanvas.lua:231
 SetPinTemplateType = <function> defined @Blizzard_MapCanvas\Blizzard_MapCanvas.lua:204
 AddOverlayFrames = <function> defined @Blizzard_WorldMap\Blizzard_WorldMap.lua:217
 SetAreaTriggerEnclosedCallback = <function> defined @Blizzard_MapCanvas\Blizzard_MapCanvas.lua:265
 IsCanvasMouseFocus = <function> defined @Blizzard_MapCanvas\Blizzard_MapCanvas.lua:739
 GetCanvasScale = <function> defined @Blizzard_MapCanvas\Blizzard_MapCanvas.lua:610
 SetGlobalAlpha = <function> defined @Blizzard_MapCanvas\Blizzard_MapCanvas.lua:911
 RemoveDataProvider = <function> defined @Blizzard_MapCanvas\Blizzard_MapCanvas.lua:117
 minimizedHeight = 534
 lockReasons = <table> {
 }
 GetScaleForMinZoom = <function> defined @Blizzard_MapCanvas\Blizzard_MapCanvas.lua:711
 NavigateToCursor = <function> defined @Blizzard_MapCanvas\Blizzard_MapCanvas.lua:790
 RemoveCursorHandler = <function> defined @Blizzard_MapCanvas\Blizzard_MapCanvas.lua:861
 AdjustDetailLayerAlpha = <functio

**Comment by Dathwada** [comment]
Thank you for reporting this error.
My last commit should fix this error, but I'm a little curious what you've done when this error occurred.

**Comment by Hollicsh** [comment]
To be honest, I don't understand how it happened ..
Most likely I opened the map and this error immediately got out.

**Comment by Dathwada** [comment]
Do you now which map you opened ?

**Comment by Hollicsh** [comment]
Most likely I opened the map in Oribos.
I can't be sure, but I think it is.
This error popped up quite unexpectedly.
According to my observations, it was after I opened the map (M).

**Comment by Hollicsh** [comment]
To be honest, I was surprised myself when I saw this error.

**Comment by Dathwada** [comment]
I tried to reproduce the error in Oribos with the version before the fix and I didn't got it, but the new version v0.3 should have fixed it. I'll close this issue now, but feel free to open it again if it should happen again with the new version.
