### ISSUE TITLE
[Feature] Ever-Shifting Mirror (retail)

### ISSUE THREAD

**Issue by p3lim** [Dathwada/handynotes-travelguide#13]
Please add support for the [Ever-Shifting Mirror](https://www.wowhead.com/item=129929/ever-shifting-mirror#comments). The wowhead comments have the mirror locations between Draenor and Outland.

Maybe use a smaller icon for these, like the ones HandyNotes: WoD uses for voidtalon portals.

**Comment by Dathwada** [comment]
Thank you for this suggestion. I didn't even know these existed. If i have enough time I'll probably add them.

How about these icons? (I'd prefer the purple portal)
![portal_purple](https://user-images.githubusercontent.com/57680823/194917143-9ff712e3-338f-4a6a-9e6f-a3e46da2afe4.png)![mirror2](https://user-images.githubusercontent.com/57680823/194917484-049d5a7f-0f3d-40fd-8dd9-8eb3e1c9b35b.png)

**Comment by Dathwada** [comment]
Added and released with [v2.11.0](https://github.com/Dathwada/handynotes-travelguide/releases/tag/Retail-v2.11.0)
