### ISSUE TITLE
[BUG] missing release.json

### ISSUE THREAD

**Issue by n9ash** [Dathwada/handynotes-travelguide#24]
The release is missing a `release.json` file. This file is necessary so that addon-managers can differentiate between different game versions of your releases. Every addon-manager that uses github (like CurseBreaker) has just "updated" the retail version of your addon to WotLKC-v1.3 ... not a good idea. :-(

**Comment by Dathwada** [comment]
Didn't know these addon-magagers need a release.json.
I've added a `release.json` to the lastest wrath and retail release here on github.

Hope this will fix it for users that are using these managers.

**Comment by n9ash** [comment]
Thank you for the quick fix. It's working now perfect. :-)
