### ISSUE TITLE
Portal Blasted Lands to Stormwind

### ISSUE THREAD

**Issue by dingsbums** [Dathwada/handynotes-travelguide#36]
**For which client is your feature request?**
Retail

**Describe the solution you'd like**
In Blasted Lands 66.4 27.9 is a portal to Stormwindsm

**Comment by Dathwada** [comment]
Thank you for letting me know that there is a portal in this zone.
I added this and other missing portals and requirements that i found on the way reviewing the portal you mentioned.

**Comment by Dathwada** [comment]
This change is now available with the new version 2.14.9.
