### ISSUE TITLE
Is it possible to transfer to API WoW 3.3.5a?[Feature] Interface: 30300

### ISSUE THREAD

**Issue by MRafStudio** [Dathwada/handynotes-travelguide#37]
== EN ==
C_QuestLog seems to be solved using GetQuestLogTitle with moving the variable inside the functions, but then problems arose with C_Map.GetMapInfo and pluginHandler:GetNodes - I understand that it should be solved using the old API or external libraries, but I couldn’t handle it. However, I am firmly convinced that it is possible to give life to your WoW addon with API 3.3.5c. For HandyNotes this will be version 1.1.5 (although, if desired, I looked, some modules can be raised to a higher level. For example, Astrolabe from 0.4 to 1.0 - it works)
Thanks for your time.
PS: Why do I even care about this? The fact is that no matter how much I searched, there is not a single example from which one could start in HandyNotes and specifically in WoW LK with Interface: 30300
Maybe I didn't search well...

== RU ==
C_QuestLog вроде как решается с помощью GetQuestLogTitle с переносом переменной внутрь функций, а потом возникли проблемы с C_Map.GetMapInfo и pluginHandler:GetNodes - понимаю, что должно быть решаемо за счет старого АПИ или внешних библиотек, но не осилил. Однако, твердо уверен дать дыхание вашему аддону под WoW c АПИ 3.3.5c возможно. Для HandyNotes это будет версия 1.1.5 (хотя при желании, я посмотрел, некоторые модули можно поднять и до более высокого уровня. Например Astrolabe с 0.4 до 1.0 - работает)
Спасибо за потраченное время.
PS: Я почему вообще пекусь о том? Дело в том, что сколько не искал - нет ни одного примера, с которого можно было бы оттолкнуться именно в HandyNotes и именно в WoW LK c Interface: 30300
Возможно плохо искал...

**Comment by Dathwada** [comment]
Hi, I'm assuming this will be for private server support on patch 3.3.5?

**Comment by MRafStudio** [comment]
Yes, that's exactly what we're talking about. Surprisingly, I discovered that for HandyNotes, in fact, there is not a single plugin that supports the 30300 interface. I myself do not know LUA, but I am writing in .NET and therefore the essence of what is happening under the hood is generally clear, but there is not enough knowledge in the WoW API.

**Comment by Dathwada** [comment]
Sry to tell you this but, I will not officially support private servers with patch 3.3.5 and the old API.

But I can give you some hints how you could get this working for yourself.

1. Download [version 1.9.3](https://www.curseforge.com/wow/addons/handynotes-travelguide/files/2551235) on Curseforge (last version before the API change) and "install" it into you AddOns Folder.
3. Remove the function `mapFile()` in `Data/db.lua`
4. Replace all `[mapFile(xxxx)]` with the mapname
(you can get the name for a zone on your open map with `/dump GetMapInfo()` )
```lua
e.g:
	["Northrend"] = { -- Northrend
		[47874119] = { portal=true, label=format(L["Portal to Stormwind"]), faction="Alliance" },
		[47894119] = { portal=true, label=format(L["Portal to Ogrimmar"]), faction="Horde" },
		[80748454] = { boat=true, label=format(L["Boat to Menethil Harbor"]), faction="Alliance" },
		[23117069] = { boat=true, label=format(L["Boat to Stormwind"]), faction="Alliance" },
		[46596733] = { boat=true, label=format(L["Boat to Unu'Pe\nBoat to Kamagua"]) },
		[29306561] = { boat=true, label=format(L["Boat to Mpa'Ki Harbor"]) },
		[67738283] = { boat=true, label=format(L["Boat to Mpa'Ki Harbor"]) },
	},
```
5. `Login`
6. Profit

tested on a 3.3.5a private server I started playing wow a long time ago.

**Comment by MRafStudio** [comment]
Even such help is very useful, especially when you are just starting to understand the issue. Thank you for the direct answer and the direction in which to look! I wish you success!

**Comment by MRafStudio** [comment]
You can’t even imagine what opportunities it opened up for me to realize my own desires! Thank you! Right now I’m sending you the current module, with my rough changes. Sorry that everything is basically in Russian. The only thing I ask is whether you will allow me, naturally while retaining all your rights, to publish my changes to your code under the same name but with a change in the product version. What I am sending you is the average option. We are only interested in your permission. If not, it's okay. All my changes to your code will not work except what is known to you and me.
[HandyNotes_TravelGuide.zip](https://github.com/Dathwada/handynotes-travelguide/files/13759901/HandyNotes_TravelGuide.zip)
