### ISSUE TITLE
The name for Eastern Kingdoms and Kalimdor in one place are not localizable

### ISSUE THREAD

**Issue by lostindark** [Dathwada/handynotes-travelguide#4]
In the top upper corner of Stormwind City where the portals to Deepholm, Uldum etc located, the Eastern Kingdoms and Kalimdor are not localizable. See screenshot below.

![WoWScrnShot_120720_005255](https://user-images.githubusercontent.com/8030927/101329881-cdf17c00-3826-11eb-97f3-d2739901b486.jpg)

**Comment by Dathwada** [comment]
Thank you for this report.
Is fixed in the next release.
