### ISSUE TITLE
[BUG] Portal icon still present for old Mythic+ portals in Oribos

### ISSUE THREAD

**Issue by slyferrain** [Dathwada/handynotes-travelguide#41]
**Describe the bug**
On the second floor of Oribos (Ring of Transference), the portal icon is still present from the portals that were there for Season 4 of Shadowlands. 

**To Reproduce**
Steps to reproduce the behavior: None.

**Expected behavior**
The icon should be removed since there are no portals there anymore.

**Screenshots**
Attached of map.

**More infos (please complete the following information):**
 - Version 2.15.0
 - Client: retail

**Additional context**

![Screenshot 2024-02-04 111229](https://github.com/Dathwada/handynotes-travelguide/assets/146494185/b0a5837f-796d-4214-a330-e9f25d840972)

**Comment by Dathwada** [comment]
Thank you for bringing this to my attention. The portals will be removed in the next release.

**Comment by Dathwada** [comment]
Released in version 2.16.0
