### ISSUE TITLE
[Feature] Missing Bel'ameth Portal in Mount Hyjal. 

### ISSUE THREAD

**Issue by slyferrain** [Dathwada/handynotes-travelguide#42]
**For which client is your feature request?**
Retail

**Is your feature request related to a problem? Please describe.**
Not really.

**Describe the solution you'd like**
Missing Bel'ameth Portal in Mount Hyjal, right next to the Stormwind portal at 62.45, 22.71.

**Comment by Dathwada** [comment]
There has to be some requirements to even see the portal, because I can't find it.

![WoWScrnShot_020524_165310](https://github.com/Dathwada/handynotes-travelguide/assets/57680823/6696f615-5810-480e-a32b-446161d7a2f5)

**Comment by slyferrain** [comment]
Hmm. Okay. I will check on an alt today to see if they can see it since I can see it on my main. I wonder if its linked to the recent questlines added with 10.2.5.

**Comment by Dathwada** [comment]
Looks like they fixed it, because I can now see the portal.

**Comment by Dathwada** [comment]
Released in version 2.16.0
