### ISSUE TITLE
10.2.7 New boats

### ISSUE THREAD

**Issue by nanjuekaien1** [Dathwada/handynotes-travelguide#45]
https://www.wowhead.com/cn/news/new-belameth-to-gilneas-ship-travel-path-in-patch-10-2-7-friendship-endures-338679

**Comment by nanjuekaien1** [comment]
It looks like the routes were removed within version number 10.2.7.5449.
to be checked

**Comment by Dathwada** [comment]
Hi, I checked and the route is still there. I will add this with the release for patch 10.2.7.

**Comment by nanjuekaien1** [comment]
###  前往风谷村（吉尔尼斯）的船
![巨龙航线](https://github.com/Dathwada/handynotes-travelguide/assets/2303601/c03d24bc-4068-45fd-ab69-0bbfed5b4b54)
### 前往贝拉纳尔（贝拉梅斯）的船
![老狼家8](https://github.com/Dathwada/handynotes-travelguide/assets/2303601/424be4df-4e63-4ad1-a7f7-ea9d21f317a2)

**Comment by nanjuekaien1** [comment]
ty
