### ISSUE TITLE
[Feature]"Suggestion for flight master locations."

### ISSUE THREAD

**Issue by Sirkgust** [Dathwada/handynotes-travelguide#50]
"I would like to know the locations of the flight instructors from all expansions. This is due to my visual impairment."**For which client is your feature request?**"I understand that this is not something urgent and it might take some time. Since The War Within is the current expansion, it would be helpful to know the locations of the flight points in this new expansion. With TomTom, I should be able to reach the exact location. If the request is accepted, or not, thank you for the assistance."
R
Retail, BCC or Classic

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Dathwada** [comment]
I have no plans to implement any flightmasters in this addon.

Everywhere you see this icon on the world map should be a flightmaster.
![grafik](https://github.com/user-attachments/assets/851278c2-dbe0-4fb8-8826-e415341ee69b)

**Comment by Dathwada** [comment]
As I do not plan to implement the Fligthmasters in this addon and there was no reply to my message, I am closing this now.
