### ISSUE TITLE
[Feature] Cata Molten Front Portal

### ISSUE THREAD

**Issue by orionshock** [Dathwada/handynotes-travelguide#53]
**For which client is your feature request?**
Cata

**Describe the solution you'd like**
Add Molten Front Portal in Hyjal

**Additional context**
Hyjal -> Molten Front
mapID: 198
cords: 27.5, 56.4
Quest Pre Req: https://www.wowhead.com/cata/quest=29201/through-the-gates-of-hell

Molten Front -> Hyjal
mapID: 338
cords: 53.0, 83.7

**Comment by Dathwada** [comment]
I have just released new versions of the Retail and Cata addons that include this portal.
