### ISSUE TITLE
[LUA Errors Patch 11.0.7]

### ISSUE THREAD

**Issue by JesperLive** [Dathwada/handynotes-travelguide#57]
**Describe the bug**
Getting a few LUA errors

**To Reproduce**
Log in to the world

**Expected behavior**
No errors

**More infos (please complete the following information):**
 - Version V2.20.0
 - Client Retails

**Additional context**

[LUA Error 1](https://pastecode.io/s/vaowubjh)
[LUA Error 2](https://pastecode.io/s/k20818p9)

**Comment by Dathwada** [comment]
duplicate of #56
