### ISSUE TITLE
Suggestion: Dungeon entrances

### ISSUE THREAD

**Issue by VirgilRex** [Dathwada/handynotes-travelguide#6]
I would like to suggest a new category to add to this addon.

Dungeon entrances, basically to see on your map where are all the dungeons entrances and be able to use them as tomtom waypoints as we can actually do with all the other things in this addon.

Right now I am manually marking them on my map using normal handynotes landmarks, but I fell like this would be a nice addition

**Comment by Dathwada** [comment]
Hey - Another addon autor has already published an handynotes plugin with [dungeon and raid](https://www.curseforge.com/wow/addons/handynotes_dungeonlocations-classic) entrances.

**Comment by VirgilRex** [comment]
Oh! Ok. I'm Sorry. I couldn't seem to find it with my addon browser. I guess it was case-sensitive. Thank you for poiting this to me. Your addon is very good though, very useful and well-made.

**Comment by Dathwada** [comment]
Thanks, yeah the dungeon addon doesn't show up in the curseforge client but there is a BCC version on the website.
