### ISSUE TITLE
 Siren Isle Mole Machine Transport

### ISSUE THREAD

**Issue by nanjuekaien1** [Dathwada/handynotes-travelguide#60]
Mole Machine Transport

https://www.wowhead.com/object=475936/mole-machine-transport
zhCN=“前往​喧鸣深窟的钻探机”

https://www.wowhead.com/object=494956/mole-machine-transport

zhCN=“前往海妖岛的钻探机”

**Comment by Dathwada** [comment]
I'll add them later today.

So the translations would be?:
L["Mole Machine to Gundargaz"] = "前往​喧鸣深窟的钻探机"
L["Mole Machine to Siren Isle"] = "前往海妖岛的钻探机"

**Comment by nanjuekaien1** [comment]
yes
Thanks

**Comment by pepedressingroom** [comment]
This year Feast of Winter Veil, an npc (Father Winter's Helper <[Express Transportation]>)who actually takes ye to Hillsbrad Foothills (right next to the greench daily)!
Ironforge:
coord(87: 31817323) npc(234715)
Orgrimmar: 
coord(85: 50367954) npc(234727)

**Comment by Dathwada** [comment]
@nanjuekaien1 I just released a new version with the mole machines.

@pepedressingroom Since I haven't added any other holiday “portals” (yet), I don't think I'll add this one either. Maybe for next year.
