### ISSUE TITLE
Petbattle unlocked teleports that are account wide and permanant. These are missing from addon

### ISSUE THREAD

**Issue by Booggg** [Dathwada/handynotes-travelguide#7]
Copy of a wowhead posted comment https://www.wowhead.com/quest=56491/tiny-terrors-of-stratholme#comments:id=3226248
"In BFA (as of Aug 2020) you can access Manapoof in 2 locations:

    Manapoof - in the pet store in Dalaran, near Krasus Landing
    Manapoof - in Boralus (Alliance city)
    Manapoof - in Dazar'Alor (Horde city)
    (OK, technically that's three locations, but without fighting into the other faction's city you'll only have convenient access to two.)

You can unlock teleports to:

    Manapoof Link: Gnomeregan after you complete Gnomeregan's New Guardians
    Manapoof Link: Stratholme after you complete Tiny Terrors of Stratholme
    Manapoof Link: Westfall after you complete The Deadmines Strike Back
    Manapoof Link: Blackrock Depths after you complete Shadows of Blackrock
    Manapoof Link: Wailing Caverns after you complete Wailing Critters"

The stratholme tele saved a good 5min of flying for alliance and these are fairly unknow shortcuts would be nice to have them added.

**Comment by Dathwada** [comment]
Thanks for your suggestion i'll add the pet battle portals.

**Comment by Dathwada** [comment]
Added in v2.6
